name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main     # или master, в зависимости от главной ветки

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build project
        run: bunx vite build
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages